#
 #  SPDX-FileCopyrightText: 2025 Edgar Huerta Mendoza <ed.huerta.m@hotmail.com>
 #  SPDX-FileCopyrightText:2025 @edhm
 #  SPDX-License-Identifier: MIT
#
services:
  react-dev:
    container_name: react-portable
    image: node:22
    working_dir: /workspace/app
    ports:
      - "5173:5173"
    volumes:
      # Monta TODO el proyecto
      - ./app:/workspace/app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    stdin_open: true
    tty: true
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"